apiVersion: v1
kind: Secret
metadata:
  name: cluster-viewer-token # cluster-viewer-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: cluster-viewer
type: kubernetes.io/service-account-token
