apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lcuwwb-foundation-dev-sa-rb
  namespace: lcuwwb-foundation-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lcuwwb-foundation-dev-sa-role
subjects:
- kind: ServiceAccount
  name: lcuwwb-foundation-dev-sa
  namespace: default
